In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [2]:
sonar_data=pd.read_csv('../Datasets/sonar data.csv')

In [3]:
sonar_data.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [4]:
sonar_data['R']=sonar_data['R'].map({'R':0,'M':1})

In [5]:
sonar_data.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  0  
1  0.0095  0.0078  0  
2  0.0040  0.0117  0  
3  0.0107  0.0094  0  
4  0.0051  0.0062  0  

[5 rows x 61 columns]

**Divide Dataset in feature and target**

In [6]:
features=sonar_data.drop(columns='R',axis=1)
target=sonar_data['R']

**Data Standardization**

In [7]:
scaler=StandardScaler()
scaler.fit(features)
features=scaler.transform(features)

In [8]:
features

array([[ 0.70018948,  0.42042142,  1.0529498 , ..., -0.4709383 ,
        -0.44268846, -0.42246083],
       [-0.13089402,  0.59942737,  1.71912994, ...,  1.30656071,
         0.25299833,  0.25405324],
       [-0.83579208, -0.64754631,  0.48045125, ..., -0.54822087,
        -0.63683361,  1.03005467],
       ...,
       [ 1.00042384,  0.15949749, -0.67235266, ...,  0.90469137,
        -0.0382194 , -0.68112798],
       [ 0.0475061 , -0.09535845,  0.13434985, ..., -0.00724291,
        -0.70154866, -0.34287094],
       [-0.13959647, -0.06501846, -0.78685237, ..., -0.67187297,
        -0.2970796 ,  0.99025973]])

**Train Test Split**

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(features,target,test_size=0.2,random_state=2)

In [10]:
print(sonar_data.shape,X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(207, 61) (165, 60) (42, 60) (165,) (42,)


**Training the Model**

In [13]:
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression()

**Model Evaluation :Accuracy Score**

In [14]:
predicted_Y_train=classifier.predict(X_train)
accuracy_score(Y_train,predicted_Y_train)

0.9212121212121213

In [15]:
predicted_Y_test=classifier.predict(X_test)
accuracy_score(Y_test,predicted_Y_test)

0.7857142857142857

**Creating Prediction System**

In [16]:
input_data=(0.0093,0.0269,0.0217,0.0339,0.0305,0.1172,0.1450,0.0638,0.0740,0.1360,0.2132,0.3738,0.3738,0.2673,0.2333,0.5367,0.7312,0.7659,0.6271,0.4395,0.4330,0.4326,0.5544,0.7360,0.8589,0.8989,0.9420,0.9401,0.9379,0.8575,0.7284,0.6700,0.7547,0.8773,0.9919,0.9922,0.9419,0.8388,0.6605,0.4816,0.2917,0.1769,0.1136,0.0701,0.1578,0.1938,0.1106,0.0693,0.0176,0.0205,0.0309,0.0212,0.0091,0.0056,0.0086,0.0092,0.0070,0.0116,0.0060,0.0110)
input_data_as_nparr=np.asarray(input_data)
input_data_reshaped=input_data_as_nparr.reshape(1,-1)
standard_input_data=scaler.transform(input_data_reshaped)
predicted_y=classifier.predict(standard_input_data)
if(predicted_y==1):
    print('Mine detected!!!!!!')
else:
    print("It's just a Rock.")

It's just a Rock.


/Users/arpitpatel/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [17]:
input_data_as_nparr

array([0.0093, 0.0269, 0.0217, 0.0339, 0.0305, 0.1172, 0.145 , 0.0638,
       0.074 , 0.136 , 0.2132, 0.3738, 0.3738, 0.2673, 0.2333, 0.5367,
       0.7312, 0.7659, 0.6271, 0.4395, 0.433 , 0.4326, 0.5544, 0.736 ,
       0.8589, 0.8989, 0.942 , 0.9401, 0.9379, 0.8575, 0.7284, 0.67  ,
       0.7547, 0.8773, 0.9919, 0.9922, 0.9419, 0.8388, 0.6605, 0.4816,
       0.2917, 0.1769, 0.1136, 0.0701, 0.1578, 0.1938, 0.1106, 0.0693,
       0.0176, 0.0205, 0.0309, 0.0212, 0.0091, 0.0056, 0.0086, 0.0092,
       0.007 , 0.0116, 0.006 , 0.011 ])

In [18]:
input_data_reshaped

array([[0.0093, 0.0269, 0.0217, 0.0339, 0.0305, 0.1172, 0.145 , 0.0638,
        0.074 , 0.136 , 0.2132, 0.3738, 0.3738, 0.2673, 0.2333, 0.5367,
        0.7312, 0.7659, 0.6271, 0.4395, 0.433 , 0.4326, 0.5544, 0.736 ,
        0.8589, 0.8989, 0.942 , 0.9401, 0.9379, 0.8575, 0.7284, 0.67  ,
        0.7547, 0.8773, 0.9919, 0.9922, 0.9419, 0.8388, 0.6605, 0.4816,
        0.2917, 0.1769, 0.1136, 0.0701, 0.1578, 0.1938, 0.1106, 0.0693,
        0.0176, 0.0205, 0.0309, 0.0212, 0.0091, 0.0056, 0.0086, 0.0092,
        0.007 , 0.0116, 0.006 , 0.011 ]])

In [19]:
standard_input_data

array([[-0.86625063, -0.35021438, -0.57606881, -0.433666  , -0.80319366,
         0.21319998,  0.37910497, -0.832533  , -0.87575741, -0.53747796,
        -0.17477832,  0.88000099,  0.7114365 , -0.18566588, -0.43061001,
         0.67760482,  1.19399192,  1.19720274,  0.4740638 , -0.4720284 ,
        -0.68348482, -0.75166733, -0.37484351,  0.26269326,  0.74902365,
         0.83793281,  0.97650675,  1.04037233,  1.23214227,  1.25098294,
         1.0457477 ,  1.08090847,  1.63724354,  2.06907005,  2.33947765,
         2.3256714 ,  2.42530811,  2.35903598,  1.6883091 ,  0.95282399,
         0.00761639, -0.60078147, -0.955367  , -1.07910575, -0.25804952,
         0.2468643 , -0.13729149, -0.35154131, -0.95696491,  0.00981094,
         1.2389928 ,  0.8045838 , -0.23099122, -0.72908022, -0.09885266,
         0.17865278, -0.13427965,  0.56464808, -0.31325836,  0.89077236]])